### PR TITLE
Add first version of Educational Sectors Vocab

### PR DESCRIPTION
**Pull request by acka47**
See https://github.com/hbz/oerworldmap/issues/570#issuecomment-287351479

### CODE REVIEW

**Comment by literarymachine** [comment]
Who is reviewing this, and what should happen if it is approved?

**Comment by acka47** [comment]
Thinking about this, I should better directly put it in https://github.com/hbz/oerworldmap/tree/master/public/json. What do you think?

For your actual question, see https://github.com/hbz/oerworldmap/issues/570#issuecomment-290037386.

**Comment by literarymachine** [comment]
> What do you think?

I think we need a concept for how exactly we will be hosting vocabs. Will ping you offline.

**Comment by acka47** [comment]
Just talked to @literarymachine that we will take this as an example to set up a vocabulary service to provide a human-readable version of any SKOS vocab. This means, we will again use permanent URLs (W3id or purl.org). I will set up such a URL for this vocab.

**Pull request merged**
