### PR TITLE
add isced 2011

### PR DESCRIPTION
**Pull request by ComeIn-NRW**
@acka47 W3ID needs to be set up: https://w3id.org/kim/isced-2011/

### CODE REVIEW

**Comment by acka47** [comment]
We could also move this to the dini-ag-kim organization on GitHub. This repo was set up and used in the context of the OER World Map project, and https://oerworldmap.org was recently shut down...

**Comment by ComeIn-NRW** [comment]
Which repository do you suggest? I'd suggest to keep the w3id links intact (and just change the location of the ttl files)

**Comment by acka47** [comment]
> Which repository do you suggest?

I didn't think about changing any structure. I'd just hand over the ownership of the repo from hbz to dini-ag-kim and than updated the w3id links.

> I'd suggest to keep the w3id links intact 

Yes, for the `class` links that are currently working. We have never used the ISCED vocabs (as we created and used [ESC](https://w3id.org/class/esc/) based on ISCED-2013). So it is no problem to change the isced links.

**Comment by ComeIn-NRW** [comment]
@acka47 
In my opinion you can move the repo and set up the w3id links.

So I can swap the w3id Links in all files

**Pull request merged**
